@startmindmap

title Основы технической документации

* Введение
** Понятие технической документации
*** Жанры технической документации
*** ГОСТы и стандарты
** Инструменты, техники и Docs as Code
*** Сбор и анализ требований
*** Контроль качества и тестирование
*** Локализация и сопровождение двуязычной документации
*** Управление изменениями и обратная связь

@endmindmap